### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by akeshavan** [SwipesForScience/SwipesForScience#11]

**Comment by Okamille** [comment]
I'm still wanting to have some tests because it will be a pain to write if we wait more :) so I think I will implement a simpler pipeline to run some tests on my own

**Comment by Okamille** [comment]
I managed to setup the project correctly, so it should work now ... The problem was the vue2-hammer module which was not included in the the transpile. I'm not sure if the package.json is correct tho, might want to check that.
The PR is here : #24
