### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by akeshavan** [SwipesForScience/SwipesForScience#25]
We should add Travis-CI to run `npm run test` on this repo

**Comment by Okamille** [comment]
I've never used Travis or CI in general, so it might be better if you add the configuration yourself !

**Comment by akeshavan** [comment]
So I have it running the unit tests fine, but the e2e tests fail because Selenium can't open https://travis-ci.org/SwipesForScience/SwipesForScience/builds/443324686 -- I also get an error on my computer

@Okamille do the e2e tests work for you?

**Comment by akeshavan** [comment]
ah, other people are having this problem: https://github.com/vuejs-templates/webpack/issues/266

**Comment by akeshavan** [comment]
hm actually it looks like they recommend sauce labs, but we'd have to pay. So I'm going to turn off the e2e tests and we'll just focus on unit now

**Comment by akeshavan** [comment]
done! https://travis-ci.org/SwipesForScience/SwipesForScience/builds/443331685
