### ISSUE TITLE
We might want to create a new widget that allow for more than two choices

### ISSUE THREAD

**Issue by Okamille** [SwipesForScience/SwipesForScience#37]
I'm thinking about creating that type of widget, I'm wanting to disable swipe because it would be too confusing (even tho it's a bit weird for SFS I reckon), and we need to find a way to place the "help" button correctly

**Comment by akeshavan** [comment]
Haha, its ok if some widgets don't swipe. Maybe lets place the help button below the card, and then allow the user to specify the number of options, and how they are coded, and those buttons can line along the bottom of the card, something like this?        

<img width="331" alt="screen shot 2018-10-26 at 10 03 19 am" src="https://user-images.githubusercontent.com/972008/47581497-64dc7200-d906-11e8-9169-268836d7c916.png">

**Comment by Okamille** [comment]
I like your design, I'll try to implement it :muscle:
