### ISSUE TITLE
Control stimulus timing

### ISSUE THREAD

**Issue by jyeatman** [SwipesForScience/SwipesForScience#86]
We need to be able to configure how long the stimulus is present on the screen and, ideally, the time interval between stimuli. This should be a parameter that is easy for the user to set.
Here is one way that might work: https://www.sitepoint.com/creating-accurate-timers-in-javascript/
Alternatively, [psychoJS](https://github.com/psychopy/psychojs) and [jsPsych ](https://www.jspsych.org/)both have impeccable timing. Maybe we can borrow functions from these packages
requestAnimationFrame might also work

**Comment by akeshavan** [comment]
I think the best way to do this is to create a widget for it, and then definitely borrow timing functions from those packages
