### ISSUE TITLE
Log response time relative to image presentation rather than image load

### ISSUE THREAD

**Issue by jyeatman** [SwipesForScience/SwipesForScience#92]
right now response time is counted from the beginning of loading the image. This means response time will be longer for slower bandwidths. We want to change this to be logged starting when the image is displayed. Look into requestAnimationFrame
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Comment by akeshavan** [comment]
Currently the time is calcuated at the Play.vue level: https://github.com/SwipesForScience/SwipesForScience/blob/master/src/components/Play.vue#L436

The widget itself should probably keep track of when its image loaded, and keep track of it in the `response` object that's passed into this function from the widget, and you can just ignore the `timeDiff` variable
